Feature/primary disability
edanalytics/edu_edfi_source pull request #32
Opened 2023-06-12 12:19 UTC by ryanaguilar

2023-06-13 01:03 UTC, ejoranlienea requested changes
These disability-sets are associated with particular program enrollments, not just particular students, so this would need to contain all the keys necessary to associate with one enrollment, that being:
`'k_student, k_program, program_enroll_begin_date, school_year'`

So we'll need those, and then some of the others (like the ed-org associated ones) could perhaps be removed, given they can be recovered from the link to the parent table.

Could be worth considering a `k_student_program_enrollment` to make that join easier to manage? Such an object could be generic across program types. What do you think @rlittle08?

The double-flatten is also worth considering as the comment points out -- not sure what the use-case for these designations is, or whether they're populated in practice, but it definitely introduces grain issues.

2023-06-14 16:02 UTC, rlittle08 commented
@ejoranlienea I think that makes sense, will make joins safer and more efficient. The only downside is that it's potentially confusing to a user that a `k_` column doesn't _always_ reference a dimension. But maybe we've already broken that rule elsewhere?

2023-06-28 18:51 UTC, rlittle08 commented
@ejoranlienea we'd like to go ahead and merge this along with the edu_wh PR here - https://github.com/edanalytics/edu_wh/pull/61/files

We will need a follow up branch to address the quality-of-life improvement for `k_student_program_enrollment`. Can you do a final review on these two PRs

2023-06-30 21:42 UTC, ejoranlienea approved these changes

2023-06-30 21:42 UTC, merged