Student academic records - switch k_student to k_student_xyear
edanalytics/edu_edfi_source pull request #55
Opened 2023-12-11 19:53 UTC by sleblanc23

## Description & motivation

## Changes to existing files:
- `_edfi_3__stage.yml` : 
- `stg_ef3__student_academic_records` : 

## Tests and QC done (together with ):
- Confirmed that row counts were unchanged in Jeffco

## PR Merge Priority:
Low - note

2023-12-15 21:39 UTC, rlittle08 requested changes

2023-12-15 21:39 UTC, rlittle08 commented on models/staging/edfi_3/stage/stg_ef3__student_academic_records.sql
>              order_by='pull_timestamp desc'
can we add `api_year desc` in the order by to keep the later ODS as source of truth where there's overlap?

2023-12-15 21:39 UTC, rlittle08 commented on models/staging/edfi_3/stage/stg_ef3__student_academic_records.sql
can we repeat this change on stg course transcripts?

2023-12-18 17:14 UTC, sleblanc23 commented on models/staging/edfi_3/stage/stg_ef3__student_academic_records.sql
>              order_by='pull_timestamp desc'
thanks for catching that! fixed

2023-12-20 23:14 UTC, ejoranlienea approved these changes

2023-12-20 23:14 UTC, merged